services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: text_miner_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    environment:
      - PYTHONUNBUFFERED=1
